### ISSUE TITLE
Let python clients run automatically from the java server?

### ISSUE THREAD

**Issue by karl-zschiebsch** [seekers-dev/seekers#24]
The runtime of java can execute commands. That makes it for example possible to run a python file when the server starts. What do you think, would this be useful?

**Comment by Belissimo-T** [comment]
@karl-zschiebsch 
I thought about that, too. This would be very useful. 
You can just execute the `run_clients.py`. You can get additional help by using the `-h` flag.

**Comment by Belissimo-T** [comment]
I created a project regarding that matter.
